# Generated by Django 4.0.3 on 2023-04-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2nd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.IntegerField(max_length=10),
        ),
    ]
