# Generated by Django 4.0.3 on 2023-04-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2nd', '0002_alter_userdetails_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
